name: build

on: [push]

jobs:
  core-dockcross:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        target: [manylinux2014-x64,manylinux2014-x86,manylinux2014-aarch64,windows-shared-x64-posix]
    steps:
      - uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0 # for git-restore-mtime
          submodules: recursive
      - uses: chetan/git-restore-mtime-action@v1.2
      - name: Setup dockcross
          docker pull dockcross/${{ matrix.target }}:latest
          docker run --rm dockcross/${{ matrix.target }}:latest > dockcross
          chmod +x dockcross
          pwd
          ls -al dockcross
      - run: ls
      - run: pwd
      - run: ./compile-dockcross.sh
